# Generated by Django 3.0.5 on 2020-04-18 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0003_notes_fk_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='fk_tag',
        ),
    ]
