# Generated by Django 3.0.5 on 2020-04-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0004_remove_notes_fk_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='fk_tag',
            field=models.ManyToManyField(to='News.Tags', verbose_name='Тэги'),
        ),
    ]
